### ISSUE TITLE
Challenge blocks

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/challenge-tp-condition#18]
Hi! I don't think this a bug, maybe more of a question. Is it possible (using this app or another) to control a block's visibility in vtex? Let's say I don't want to show the minicart if the user is not loggedin. I've tried the following code, but no luck.

```
"minicart.v2": {
      "props": {
        "MinicartIcon": "icon-cart#minicart-icon"
      },
      "children": ["minicart-base-content"],
      "parent": {
        "challenge": "challenge.trade-policy-condition#login"
      }
    },
```

Is this app designed to work like this? The challenge is working if used as in the documentation, with a parent on the store.home interface, but not on a block.

You can test this functionality here: https://beta--vetrob2c.myvtex.com/

Thanks!

**Comment by klzns** [comment]
You can use this app instead:
https://github.com/vtex-apps/auth-challenge
