### ISSUE TITLE
challenge.trade-policy-condition not working on product page

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/challenge-tp-condition#19]
**Describe the bug**
Hi! When I add a challenge to the store.product interface, when I access the product page I get 404 instead of a redirect from the policy condition.

**To Reproduce**

1. Define a trade policy condition
2. Add the challenge to the store.product interface.

See code bellow:

```json
 "store.product": {
    "children": [
      "flex-layout.row#product-breadcrumb",
      "flex-layout.row#product-main",
      "flex-layout.row#description",
      "shelf.relatedProducts"
    ],
    "parent": {
      "challenge": "challenge.trade-policy-condition#login"
    }
  },
```

**Expected behavior**
Should redirect to the trade-policy-condition redirect rule

**Screenshots**
![image](https://user-images.githubusercontent.com/42587916/91549381-86a64600-e92f-11ea-9577-576acee3f4cb.png)
![image](https://user-images.githubusercontent.com/42587916/91549390-8b6afa00-e92f-11ea-978e-06d3f91f1b92.png)
![image](https://user-images.githubusercontent.com/42587916/91549416-94f46200-e92f-11ea-8e67-a97f825f7f50.png)

**Additional context**
See issue at: https://dorutest2--vetrob2c.myvtex.com/monge-natural-all-breeds-adult--miel-orez-cartof--1590/p

Thanks!

**Comment by klzns** [comment]
@doruradu can you add the challenge block to the not-found product page and see if that works?

```json
{
  "store.not-found#product": {
    "blocks": ["rich-text#not-found"],
    "parent": {
      "challenge": "challenge.trade-policy-condition#login"
    }
  }
}
```
